---
name: Linux Ubuntu Debian Build and Package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  GO111MODULE: "on"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.20' ]
        go-arch: [ 'amd64' ]
        go-opsys: [ 'linux' ]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Install dependencies
        run: go mod download -x

      - name: Build with go
        run: |
          mkdir -p build/
          GOOS=${{ matrix.go-opsys }} \
          GOARCH=${{ matrix.go-arch }} \
            go build -o build/calculateSubnets ./cmd/calculateSubnets/main.go


      - name: Set Release Version
        id: set_version
        run: |
          echo "::set-output name=version::$(date +%s)-${{ matrix.go-opsys }}-${{ matrix.go-arch }}"


      - uses: kentik/pkg@v1
        with:
          name: subnetting-${{ steps.set_version.outputs.version }}.deb
          version: ${{ steps.set_version.outputs.version }}
          arch: x86_64
          format: deb
          package: package-deb.yaml

      - uses: kentik/pkg@v1
        with:
          name: my-package
          version: 0.0.1
          arch: x86_64
          format: rpm
          package: package-deb.yaml

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ format('v{0}', steps.set_version.outputs.version) }}
          release_name: Release ${{ steps.set_version.outputs.version }}
          body: |
            This is the release of calculateSubnets ${{ steps.set_version.outputs.version }}.
          draft: false
          prerelease: false

      - name: List files
        run: ls -la
#
#      - name: Publish Artifact
#        uses: actions/upload-artifact@v2
#        with:
#          name: subnetting-${{ steps.set_version.outputs.version }}
#          path: *.deb
#
#      - name: Publish Artifact
#        uses: actions/upload-artifact@v2
#        with:
#          name: subnetting-${{ steps.set_version.outputs.version }}
#          path: *.rpm
