name: Linux Ubuntu Debian Build and Package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  GO111MODULE: "on"

jobs:
  pre-check-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.20' ]
        go-arch: [ 'amd64', 'arm64' ]
        go-opsys: [ 'linux' ]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Install dependencies
        run: go mod download -x

      - name: Test with Go
        run: |
          go test -json ./...

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.20' ]
        go-arch: [ 'amd64', 'arm64' ]
        go-opsys: [ 'linux' ]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Install dependencies
        run: go mod download -x

      - name: Build with go
        run: |
          mkdir -p build/${{ matrix.go-opsys }}/${{ matrix.go-arch }}/${{ matrix.go-version }}/
          GOOS=${{ matrix.go-opsys }} \
          GOARCH=${{ matrix.go-arch }} \
            go build -o build/${{ matrix.go-opsys }}/${{ matrix.go-arch }}/${{ matrix.go-version }}/calculateSubnets \
              ./cmd/calculateSubnets/main.go

      - name: Create Debian/Ubuntu Package
        run: |
          cd build/${{ matrix.go-opsys }}/${{ matrix.go-arch }}/${{ matrix.go-version }}/
          mkdir -p debian/DEBIAN
          touch debian/DEBIAN/control
          echo "Package: calculateSubnets" >> debian/DEBIAN/control
          echo "Version: ${{ matrix.go-version }}.$(date +%s)" >> debian/DEBIAN/control
          echo "Architecture: ${{ matrix.go-arch }}" >> debian/DEBIAN/control
          echo "Maintainer: Sam Caldwell <mail@samcaldwell.net>" >> debian/DEBIAN/control
          echo "Description: calculateSubnets binary" >> debian/DEBIAN/control
          mkdir -p debian/usr/bin
          cp calculateSubnets debian/usr/bin
          dpkg-deb --build debian
          cp debian.deb ../../../subnetting-${{ matrix.go-opsys }}/${{ matrix.go-arch }}/${{ matrix.go-version }}.deb
          ls ../../../
          pwd

  create-release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Set Release Version
        id: set_version
        run: |
          echo "::set-output name=version::${{ matrix.go-opsys }}/${{ matrix.go-arch }}.$(date +%s)"

      - name: Create Release
        id: create_release
        uses:
